version: "3.7"
services:
  project-zomboid:
    image: afey/zomboid
    restart: unless-stopped
    network_mode: host
    environment:
      SERVER_NAME: "pzserver"
      ADMIN_PASSWORD: "pzserver-password"
      SERVER_PUBLIC_NAME: ""
      SERVER_PASSWORD: ""
    ports:
      - "8766:8766/udp"           # steam port 1
      - "8767:8767/udp"           # steam port 2
      - "16261:16261/udp"         # game server port
      - "16262-16272:16262-16272" # client ports (1 port per player)
      - "27015:27015"             # rcon port
    volumes:
      - ./server-data:/server-data
      - ./server-files:/server-files
